# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78de23662f944cbe16618b8f945477ebe60db2bc6592560d949131e0e125c8088b94ae6a8384e6cf8df2f46935f0afe005e21c8c4c4094de031f81c1e3b0378f

test:
  secret_key_base: 2e94904d32f24c34242a3e0eb29467d65e612b60f74978193d377c9a5786cc3924658d9fa7e775cde6b8c3db2aa8cfa7b081be247fcd22baa6b1af88763b2be6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
